# Generated by Django 4.1 on 2023-03-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
